### ISSUE TITLE
Please clarify the primary repository: https://github.com/ongres/scram or https://gitlab.com/ongresinc/scram

### ISSUE THREAD

**Issue by vlsi** [ongres/scram#12]
Currently, it is hard to tell which is the primary: https://github.com/ongres/scram or https://gitlab.com/ongresinc/scram.

For instance, Fedora references github repository: https://src.fedoraproject.org/rpms/ongres-scram/blob/rawhide/f/ongres-scram.spec#_9
Should they update?

**Comment by jorsol** [comment]
Hi Vladimir, I created a mirror here, so the primary repo is on https://gitlab.com/ongresinc/scram, and this repo is now a mirror, so, both repos should work and are in sync.

As a mirror, the Fedora references could still point to GH (now that is a mirror), but if they can update the references to GL (since is now the primary) it should be correct.

**Comment by vlsi** [comment]
Ok, thanks. It looked like 2.1 tag was missing in github.com mirror which caused confusion.
